# -*- coding: utf-8 -*-
"""CustomerSegmentation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZOx1zvRaNY7xm2-IK7Fxza7axl3kJNPV
"""

import pandas as pd
import numpy as np

df = pd.read_csv("Mall_Customers.csv")
df.head()

df.info()

df.shape

df.isnull().sum()

df.describe()

df['Gender'].unique()

df.groupby('Age')['Annual Income (k$)'].agg(['min','max','mean']).sort_values(by='mean',ascending=False)

df['CustomerID'].shape

df.drop('CustomerID', axis=1, inplace=True)

df.shape

df['Gender']=df['Gender'].map({'Female':0, 'Male':1})

df.info()

import matplotlib.pyplot as plt
df[['Age','Annual Income (k$)','Spending Score (1-100)']].hist(figsize=(10,10))
# plt.tight_layout()
plt.show()

df[['Age','Annual Income (k$)','Spending Score (1-100)','Gender']].corr()

df[['Age','Annual Income (k$)','Spending Score (1-100)','Gender']].nunique()

final_df = df[['Age','Annual Income (k$)','Spending Score (1-100)']]

final_df.to_csv('featured_mall_customer.csv', index=False)

















