# -*- coding: utf-8 -*-
"""machine_learning_students_performance

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fG15ikmmSDfw5kuLGQtFPhVpssG2538a
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_squared_error

df=pd.read_csv('StudentsPerformance.csv')
df.head()

# df['total_score']=df['math score']+df['reading score']+df['writing score']
# df

# df.drop(['math score', 'reading score','writing score'], axis=1, inplace=True)

# df

df['gender']=df['gender'].map({'female':0,'male':1})

# df

df['race/ethnicity'].value_counts()

df['parental level of education'].value_counts()
edu_order = {
    "some high school" : 1,
    "high school" : 2,
    "some college" : 3,
    "associate's degree" : 4,
    "bachelor's degree" : 5,
    "master's degree" : 6
}
df['parental level of education'] = df['parental level of education'].map(edu_order)

df['lunch'].value_counts()

df['test preparation course'].value_counts()

df['lunch']=df['lunch'].map({'free/reduced':0,'standard':1})

df['test preparation course']=df['test preparation course'].map({'none':0,'completed':1})

df_race=pd.get_dummies(df['race/ethnicity'], drop_first=True)
df_race

df=pd.concat([df, df_race], axis=1)
df.drop(['race/ethnicity'], axis=1, inplace=True)

df

df.info()

df

# X = df[['gender', 'test preparation course', 'lunch', 'group B',	'group C',	'group D',	'group E','parental level of education']]
X = df.drop('math score', axis=1)
y = df['math score']
df.info()

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train_scaled = sc.fit_transform(X_train)
X_test_scaled = sc.transform(X_test)

model = LinearRegression()
model.fit(X_train_scaled, y_train)

y_pred = model.predict(X_test_scaled)

r2 = r2_score(y_test, y_pred)
print(r2)



